version: '3.8'

services:
  # MySQL Database Service
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: sivanaltar-mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
             --character-set-server=utf8mb4
             --collation-server=utf8mb4_unicode_ci
             --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: sivanaltar_root_password
      MYSQL_DATABASE: sivanaltar_db
      MYSQL_USER: sivanaltar_user
      MYSQL_PASSWORD: sivanaltar_password
    networks:
      - sivanaltar-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Web Application Service
  sivanaltar-website:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: sivanaltar-website
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      - DB_HOST=mysql
      - DB_NAME=sivanaltar_db
      - DB_USER=sivanaltar_user
      - DB_PASS=sivanaltar_password
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - sivanaltar-network

networks:
  sivanaltar-network:
    driver: bridge